services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-rproxy
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Atlantic/Reykjavik}
    # Bind ONLY to your LAN IP; container listens on 8080/8443 (per your configs)
    ports:
      - "${LAN_BIND:-127.0.0.1}:80:8080"
      - "${LAN_BIND:-127.0.0.1}:443:8443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD-SHELL", "/bin/busybox wget -q -O - http://127.0.0.1:8080/healthz >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    restart: "no"   # run only on demand with `docker compose run`
    environment:
      - TZ=${TZ:-Atlantic/Reykjavik}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./secrets:/secrets:ro

volumes:
  letsencrypt:
 
